// File: VGA_HDMI.v
// Generated by MyHDL 0.10
// Date: Tue Jul 10 14:22:56 2018


`timescale 1ns/10ps

module VGA_HDMI (
    clk,
    Vsync,
    Hsync,
    DataEn,
    X,
    X_5,
    Y,
    Width,
    Height,
    ResolutionSel,
    RGBI_R,
    RGBI_G,
    RGBI_B,
    RGBO_R,
    RGBO_G,
    RGBO_B
);


input clk;
output Vsync;
reg Vsync;
output Hsync;
reg Hsync;
output DataEn;
reg DataEn;
output [11:0] X;
reg [11:0] X;
output [11:0] X_5;
reg [11:0] X_5;
output [11:0] Y;
reg [11:0] Y;
output [11:0] Width;
wire [11:0] Width;
output [11:0] Height;
wire [11:0] Height;
input [2:0] ResolutionSel;
input [7:0] RGBI_R;
input [7:0] RGBI_G;
input [7:0] RGBI_B;
output [7:0] RGBO_R;
reg [7:0] RGBO_R;
output [7:0] RGBO_G;
reg [7:0] RGBO_G;
output [7:0] RGBO_B;
reg [7:0] RGBO_B;

reg [11:0] V_TOTAL = 0;
reg [6:0] V_SYNC = 0;
reg [6:0] V_B_PORCH = 0;
reg [11:0] V_ADDR = 0;
reg [11:0] VCNT = 0;
reg [11:0] H_TOTAL = 0;
reg [7:0] H_SYNC = 0;
reg [8:0] H_B_PORCH = 0;
reg [11:0] H_ADDR = 0;
reg [11:0] HCNT = 0;

assign Height = V_ADDR;
assign Width = H_ADDR;


always @(ResolutionSel, RGBI_G, RGBI_R, RGBI_B) begin: VGA_HDMI_R_SEL
    RGBO_R = RGBI_R;
    RGBO_G = RGBI_G;
    RGBO_B = RGBI_B;
    case (ResolutionSel)
        'h0: begin
            // 1280x1024@60Hz  108.0M
            H_TOTAL = 1688;
            H_ADDR = 1280;
            H_SYNC = 112;
            H_B_PORCH = 248;
            V_TOTAL = 1066;
            V_ADDR = 1024;
            V_SYNC = 3;
            V_B_PORCH = 38;
        end
        'h1: begin
            // 1440x900@60Hz 106.5M
            H_TOTAL = 1904;
            H_ADDR = 1440;
            H_SYNC = 152;
            H_B_PORCH = 232;
            V_TOTAL = 934;
            V_ADDR = 900;
            V_SYNC = 6;
            V_B_PORCH = 25;
        end
        'h2: begin
            // 1600x900@60Hz 108.0M
            H_TOTAL = 1800;
            H_ADDR = 1600;
            H_SYNC = 80;
            H_B_PORCH = 96;
            V_TOTAL = 1000;
            V_ADDR = 900;
            V_SYNC = 3;
            V_B_PORCH = 96;
        end
        'h3: begin
            // 1920*1080@60Hz 148.5M
            H_TOTAL = 2200;
            H_ADDR = 1920;
            H_SYNC = 44;
            H_B_PORCH = 148;
            V_TOTAL = 1125;
            V_ADDR = 1080;
            V_SYNC = 5;
            V_B_PORCH = 36;
        end
        default: begin
            // Test
            H_TOTAL = (((160 + 3) + 7) + 4);
            H_ADDR = 160;
            H_SYNC = 3;
            H_B_PORCH = 7;
            V_TOTAL = (((120 + 5) + 6) + 7);
            V_ADDR = 120;
            V_SYNC = 5;
            V_B_PORCH = 6;
        end
    endcase
end


always @(posedge clk) begin: VGA_HDMI_SEQ
    if (($signed({1'b0, HCNT}) == ($signed({1'b0, H_TOTAL}) - 1))) begin
        HCNT <= 0;
    end
    else begin
        HCNT <= (HCNT + 1);
    end
    if (($signed({1'b0, HCNT}) == ($signed({1'b0, H_TOTAL}) - 1))) begin
        if (($signed({1'b0, VCNT}) == ($signed({1'b0, V_TOTAL}) - 1))) begin
            VCNT <= 0;
        end
        else begin
            VCNT <= (VCNT + 1);
        end
    end
    if (((VCNT >= 0) && (VCNT < V_SYNC))) begin
        Vsync <= 0;
    end
    else begin
        Vsync <= 1;
    end
    if ((((HCNT >= 0) && (HCNT < H_SYNC)) || ((VCNT < (V_SYNC + V_B_PORCH)) || (VCNT >= ((V_SYNC + V_B_PORCH) + V_ADDR))))) begin
        Hsync <= 0;
    end
    else begin
        Hsync <= 1;
    end
    if (Hsync) begin
        X_5 <= ((HCNT + 5) - (H_SYNC + H_B_PORCH));
        X <= (HCNT - (H_SYNC + H_B_PORCH));
    end
    Y <= (VCNT - (V_SYNC + V_B_PORCH));
    DataEn <= (Hsync && (HCNT >= (H_SYNC + H_B_PORCH)) && (HCNT < ((H_SYNC + H_B_PORCH) + H_ADDR)));
end

endmodule
